name: Deploy Azure Services

on:
  push:
    branches:
      - main

jobs:
  deploy-services:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Deploy Speech Services
      - name: Deploy Speech Services ARM Template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: rg-calltranscription
          template: ./arm-templates/speech-service.json
          parameters: ./arm-templates/speech-service.parameters.json
          deploymentMode: Incremental

      # Step 4: Deploy Language Services
      - name: Deploy Language Services ARM Template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: rg-calltranscription
          template: ./arm-templates/language-service.json
          parameters: ./arm-templates/language-service.parameters.json
          deploymentMode: Incremental

      # Step 5: Deploy Existing Storage Account
      - name: Deploy Storage Account
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: rg-calltranscription
          template: ./arm-templates/storage-account.json
          parameters: ./arm-templates/storage-account.parameters.json
          deploymentMode: Incremental

      # Step 6: Validate Deployment
      - name: Validate Deployment
        run: |
          echo "Speech, Language, Blob Storage services deployed successfully!"
