name: Deploy Azure Speech Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      run: |
        az group create \
          --name rg-calltranscription \
          --location uksouth

    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        scope: resourceGroup
        subscriptionId: 4f203997-0a6d-4f66-934b-7a51ea90e3b9
        resourceGroupName: rg-calltranscription
        template: ./arm-templates/speech-service.json
        parameters: >
          location="uksouth" 
          speechServiceName="dp-AI-speech" 
          skuName="F0" 
          enableManagedIdentity=true
