name: Deploy Azure Speech Services

on:
  push:
    branches:
      - main

jobs:
  deploy-speech-service:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Deploy ARM Template with Parameters
      - name: Deploy Speech Services ARM Template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: rg-calltranscription
          template: ./speech-service.json
          parameters: ./speech-service.parameters.json
          deploymentMode: Incremental

      # Step 4: Validate Deployment
      - name: Validate Deployment
        run: |
          echo "Deployment successful!"
